Add more checks

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -14,4 +14,47 @@ jobs:
     steps:
       - uses: actions/checkout@v3
       - run: npm install
-      - run: npx prettier --check .
+
+      - name: Prettier check
+        id: prettier
+        run: |
+          npx prettier --check .
+          echo "prettier_exit_code=$?" >> $GITHUB_OUTPUT
+        continue-on-error: true
+      
+      - name: Typescript check
+        id: typescript
+        run: |
+          npx tsc --noEmit
+          echo "typescript_exit_code=$?" >> $GITHUB_OUTPUT
+        continue-on-error: true
+      
+      - name: ESLint check
+        id: eslint
+        run: |
+          npx eslint .
+          echo "eslint_exit_code=$?" >> $GITHUB_OUTPUT
+        continue-on-error: true
+
+      - name: Check results 
+        # Error if any of the checks failed
+        run: |
+          exit_code=0
+
+          if [ "${{ steps.prettier.outputs.prettier_exit_code }}" -ne 0 ]; then
+            echo "Prettier check failed"
+            exit_code=1
+          fi
+          if [ "${{ steps.typescript.outputs.typescript_exit_code }}" -ne 0 ]; then
+            echo "Typescript check failed"
+            exit_code=1
+          fi
+          if [ "${{ steps.eslint.outputs.eslint_exit_code }}" -ne 0 ]; then
+            echo "ESLint check failed"
+            exit_code=1
+          fi
+          if [ $exit_code -ne 0 ]; then
+            echo "One or more checks failed"
+          fi
+
+          exit $exit_code
